### DISCUSSION TITLE
Ignore rule globally

### DISCUSSION THREAD

**Discussion by macmessa** [DataDog/datadog-static-analyzer#674] [Q&A] [answered]
Is this the right way to ignore a rule globally in the static analysis yml?

```yml
schema-version: v1
rulesets:
  - docker-best-practices
  - tsx-react
  - typescript-best-practices:
    rules:
      boolean-prop-naming:
        ignore:
          - **/*
```

**Comment by jfree** [comment, marked as answer]
Hi Marco, 

This is an example of the global rule exclusion format that the IDE plugins/extensions generate, which is working for me on an internal project here at Datadog:

```
rulesets:
  - kotlin-code-style:
    rules:
      annotation-spacing:
        ignore:
          - "**"
```
