### ISSUE TITLE
MJS files unrecognized as Javascript

### ISSUE THREAD

**Issue by twelvelabs** [DataDog/datadog-static-analyzer#529]
**Describe the bug**

`datadog-static-analyzer` does not recognize MJS files - even if explicitly including them via config. 

**To Reproduce**

1. Download the latest linux build. I used `https://github.com/datadog/datadog-static-analyzer/releases/latest/download/datadog-static-analyzer-$(uname -m)-unknown-linux-gnu.zip`
2. Create a directory containing javascript files using the `.mjs` file extension, which is used by Node [to distinguish JS files using the ES6 module system](https://stackoverflow.com/questions/57492546/what-is-the-difference-between-js-and-mjs-files). Note, I did not try it, but I suspect this is an issue w/ `.cjs` files as well.
3. Create `static-analysis.datadog.yml`:

```yaml
rulesets:
  - javascript-best-practices
  - javascript-code-style
  - javascript-common-security
  - javascript-node-security

only:
  - "**/*.mjs"
```

6. Run `datadog-static-analyzer --directory .  --print-violations --debug yes --format json --output output.json`
7. Debug output shows files are not scanned.
8. Rename `.mjs` files to `.js` and re-run.
9. Files are correctly scanned.

**Expected behavior**

I expected the files to be scanned as javascript... or a config option that allowed me to specify that MJS files _should_ be scanned as javascript.

**Desktop (please complete the following information):**
 - OS: `node:20-slim` docker image
